apiVersion: v1
kind: Service
metadata:
  name: task-manager-service-loadbalancer
spec:
  selector:
    app: task-manager
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000